exp_name: 6DRepNet_final

agora_root: "/home/choi/hwang/workspace/etri/make_pseudoGT/dataset/full_range_head/AGORA"
cmu_root: "/home/choi/hwang/workspace/etri/make_pseudoGT/dataset/full_range_head/CMU-Panoptic"
save_path: './weight'

img_size: 224

num_epochs: 40
lr: 0.00001
batch_size: 64
num_workers: 4

milestones: [10, 20]
gamma: 0.1

seed: 42
