DATASET:
    base_path: '/home/choi/hwang/workspace/etri/datasets'
    train: 'train/scut_head.txt'
    valid: 'valid/scut_head.txt'

    max_size: 1000
    min_size: 600


TRAINING:
    exp_name: 'SCUT_up_F'
    backbone : 'resnet50'
    pretrained_model: ''
    save_dir: '/home/choi/hwang/workspace/HeadHunter/output_weights'
    start_eval: 1
    eval_period: 1
    max_epoch: 20

HYPER_PARAM:
    learning_rate: 0.0001
    momentum: 0.9
    weight_decay: 0.0005
    gamma: 0.5
    milestones: [5, 10, 15]
    batch_size: 12


NETWORK:
    use_deform: False
    ohem: True
    context: 'cpm'
    custom_sampling: False
    soft_nms: False
    upscale_rpn: False
    median_anchors: True # comb_anchors = ((12,), (32,), (64,), (112,))  # 4개의 anchor로 설정

