DATASET:
    base_path: '/home/choi/hwang/workspace/etri/datasets'
    train: 'train/scut_head.txt'
    valid: 'valid/scut_head.txt'

    mean_std: [[118.14, 110.79, 104.97], [64.45, 64.44, 65.16]]
    max_size: 1000
    min_size: 600


TRAINING:
    exp_name: 'SCUT_HDHT_ori_faster_rcnn_anchor2'
    backbone : 'resnet50'
    pretrained_model: ''
    save_dir: '/home/choi/hwang/workspace/HeadHunter/output_weights'
    start_eval: 1
    eval_period: 1
    max_epoch: 30
    AMP: True

HYPER_PARAM:
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.0005
    gamma: 0.5
    milestones: [5, 10, 15]
    batch_size: 4


NETWORK:
    use_deform: False
    ohem: False
    context: # cpm, deform_ssh, ssh
    custom_sampling: False
    soft_nms: False
    upscale_rpn: False
    median_anchors: True # comb_anchors = ((12,), (32,), (64,), (112,))  # 4개의 anchor로 설정
#    anchors:
#      - [12]
#      - [32]
#      - [112]
#      - [256]
#    anchors:
#      - [18]
#      - [36]
#      - [72]
#      - [128]
#    anchors:
#        - [32]
#        - [64]
#        - [128]
#        - [256]
    anchors:
        - [18]
        - [36]
        - [72]
        - [128]
    aspect_ratios:
      - [0.5, 1.0, 1.5]
